config/routes.rb
Rails.application.routes.draw do
  resources :female_transaksis
  resources :male_transaksis
  resources :koleksi_jurnals
  resources :akuns
  devise_for :users
end

app/models/koleksi_jurnal.rb
class KoleksiJurnal < ApplicationRecord
  belongs_to :user
  has_many :jurnals
end

app/controllers/koleksi_jurnals_controller.rb
class KoleksiJurnalsController < ApplicationController
  before_action :set_koleksi_jurnal, only: [:show, :edit, :update, :destroy]

  # GET /koleksi_jurnals
  def index
    @koleksi_jurnals = KoleksiJurnal.all
  end

  # GET /koleksi_jurnals/1
  def show
  end

  # GET /koleksi_jurnals/new
  def new
    @koleksi_jurnal = KoleksiJurnal.new
  end

  # GET /koleksi_jurnals/1/edit
  def edit
  end

  # POST /koleksi_jurnals
  def create
    @koleksi_jurnal = KoleksiJurnal.new(koleksi_jurnal_params)

    if @koleksi_jurnal.save
      redirect_to @koleksi_jurnal, notice: 'Koleksi jurnal was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /koleksi_jurnals/1
  def update
    if @koleksi_jurnal.update(koleksi_jurnal_params)
      redirect_to @koleksi_jurnal, notice: 'Koleksi jurnal was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /koleksi_jurnals/1
  def destroy
    @koleksi_jurnal.destroy
    redirect_to koleksi_jurnals_url, notice: 'Koleksi jurnal was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_koleksi_jurnal
      @koleksi_jurnal = KoleksiJurnal.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def koleksi_jurnal_params
      params.require(:koleksi_jurnal).permit(:user_id)
    end
end

app/helpers/koleksi_jurnals_helper.rb
module KoleksiJurnalsHelper
end

app/views/koleksi_jurnals/_form.html.erb
<%= form_for(@koleksi_jurnal, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @koleksi_jurnal.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@koleksi_jurnal.errors.count, "error") %> prohibited this koleksi_jurnal from being saved:</h4>

      <ul>
      <% @koleksi_jurnal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :user, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/koleksi_jurnals/edit.html.erb
<div class="page-header">
  <%= link_to koleksi_jurnals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @koleksi_jurnal, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing koleksi_jurnal</h1>
</div>

<%= render 'form' %>

app/views/koleksi_jurnals/index.html.erb
<div class="page-header">
  <%= link_to new_koleksi_jurnal_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Koleksi jurnal
  <% end %>
  <h1>Listing koleksi_jurnals</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>User</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @koleksi_jurnals) do |koleksi_jurnal| %>
            <td><%= koleksi_jurnal.user %></td>
            <td><%= link_to 'Show', koleksi_jurnal %></td>
        <td><%= link_to 'Edit', edit_koleksi_jurnal_path(koleksi_jurnal) %></td>
        <td><%= link_to 'Destroy', koleksi_jurnal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/koleksi_jurnals/new.html.erb
<div class="page-header">
  <%= link_to koleksi_jurnals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New koleksi_jurnal</h1>
</div>

<%= render 'form' %>

app/views/koleksi_jurnals/show.html.erb
<div class="page-header">
  <%= link_to koleksi_jurnals_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_koleksi_jurnal_path(@koleksi_jurnal), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show koleksi_jurnal</h1>
</div>

<dl class="dl-horizontal">
  <dt>User:</dt>
  <dd><%= @koleksi_jurnal.user %></dd>

</dl>