config/routes.rb
Rails.application.routes.draw do
  resources :female_transaksis
  resources :male_transaksis
  resources :koleksi_jurnals
  resources :akuns
  devise_for :users
end

app/models/jurnal.rb
class Jurnal < ApplicationRecord
  belongs_to :koleksi_jurnal
  has_many :male_transaksis
  has_many :female_transaksis
end

app/controllers/jurnals_controller.rb
class JurnalsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_jurnal, only: [:show, :edit, :update, :destroy]

  # GET /jurnals
  def index
    @jurnals = Jurnal.all.paginate(page: params[:page], per_page: 30)
  end

  # GET /jurnals/1
  def show
  end

  # GET /jurnals/new
  def new
    @jurnal = Jurnal.new
  end

  # GET /jurnals/1/edit
  def edit
  end

  # POST /jurnals
  def create
    @jurnal = Jurnal.new(jurnal_params)

    if @jurnal.save
      redirect_to @jurnal, notice: 'Jurnal was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /jurnals/1
  def update
    if @jurnal.update(jurnal_params)
      redirect_to @jurnal, notice: 'Jurnal was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /jurnals/1
  def destroy
    @jurnal.destroy
    redirect_to jurnals_url, notice: 'Jurnal was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jurnal
      @jurnal = Jurnal.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def jurnal_params
      params.require(:jurnal).permit(:akun_id, :deskripsi, :saldo)
    end
end

app/helpers/jurnals_helper.rb
module JurnalsHelper
end

app/views/jurnals/_form.html.erb
<div class="flex-container">
  <%= simple_form_for(@jurnal) do |f| %>
    <div class="form-inputs">
      <%= f.association :akun, label_method: :nama, prompt: 'Pilih...', label: false, class: 'flex-input' %>
      <%= f.input :deskripsi, label: false, placeholder: 'Keterangan', class: 'flex-input' %>
      <%= f.input :saldo, label: false, placeholder: 'Nominal', class: 'flex-input' %>
    </div>
    <div class="flex-item pull-right">
      <div class="form-actions">
        <span class="form-notif">press 'Enter' when done</span>
      </div>
    </div>
    <%= f.button :submit, class: 'hidden-button' %>
  <% end %>
</div>

app/views/jurnals/edit.html.erb
<h1>Editing Jurnal</h1>

<%= render 'form', jurnal: @jurnal %>

<%= link_to 'Show', @jurnal %> |
<%= link_to 'Back', jurnals_path %>

app/views/jurnals/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="row">
        <div class="col-xs-12" style="margin-bottom: 10px;">
          <div class="text-right">
            <%= link_to 'New Jurnal', new_jurnal_path %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
          </div>
        </div>
        <div class="col-xs-12">
          <div class="panel">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th>Kode</th>
                    <th>Nama</th>
                    <th>Deskripsi</th>
                    <th>Debit/Kredit</th>
                    <th>Saldo</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @jurnals.each do |jurnal| %>
                    <tr>
                      <td><%= jurnal.akun.kode %></td>
                      <td><%= jurnal.akun.nama %></td>
                      <td><%= jurnal.deskripsi %></td>
                      <td><%= jurnal.akun.tipe_akun.nama %></td>
                      <td><%= jurnal.saldo %></td>
                      <td><%= link_to 'Show', jurnal, class:'small-link-reverse' %></td>
                      <td><%= link_to 'Edit', edit_jurnal_path(jurnal), class:'small-link-reverse' %></td>
                      <td><%= link_to 'Destroy', jurnal, method: :delete, data: { confirm: 'Are you sure?' }, class:'small-link-reverse' %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
          <%= will_paginate @jurnals %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/jurnals/new.html.erb
<h1>New Jurnal</h1>

<%= render 'form', jurnal: @jurnal %>

<%= link_to 'Back', jurnals_path %>

app/views/jurnals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Akun:</strong>
  <%= @jurnal.akun %>
</p>

<p>
  <strong>Deskripsi:</strong>
  <%= @jurnal.deskripsi %>
</p>

<p>
  <strong>Saldo:</strong>
  <%= @jurnal.saldo %>
</p>

<%= link_to 'Edit', edit_jurnal_path(@jurnal) %> |
<%= link_to 'Back', jurnals_path %>