config/routes.rb
Rails.application.routes.draw do
  resources :female_transaksis
  resources :male_transaksis
  resources :koleksi_jurnals
  resources :akuns
  devise_for :users
end

app/models/male_transaksi.rb
class MaleTransaksi < ApplicationRecord
  belongs_to :akun
  belongs_to :tipe_relasi
  belongs_to :jurnal
end

app/controllers/male_transaksis_controller.rb
class MaleTransaksisController < ApplicationController
  before_action :set_male_transaksi, only: [:show, :edit, :update, :destroy]

  # GET /male_transaksis
  def index
    @male_transaksis = MaleTransaksi.all
  end

  # GET /male_transaksis/1
  def show
  end

  # GET /male_transaksis/new
  def new
    @male_transaksi = MaleTransaksi.new
  end

  # GET /male_transaksis/1/edit
  def edit
  end

  # POST /male_transaksis
  def create
    @male_transaksi = MaleTransaksi.new(male_transaksi_params)

    if @male_transaksi.save
      redirect_to @male_transaksi, notice: 'Male transaksi was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /male_transaksis/1
  def update
    if @male_transaksi.update(male_transaksi_params)
      redirect_to @male_transaksi, notice: 'Male transaksi was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /male_transaksis/1
  def destroy
    @male_transaksi.destroy
    redirect_to male_transaksis_url, notice: 'Male transaksi was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_male_transaksi
      @male_transaksi = MaleTransaksi.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def male_transaksi_params
      params.require(:male_transaksi).permit(:akun_id, :deskripsi, :nominal, :tipe_relasi_id, :jurnal_id)
    end
end

app/helpers/male_transaksis_helper.rb
module MaleTransaksisHelper
end

app/views/male_transaksis/_form.html.erb
<%= form_for(@male_transaksi, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @male_transaksi.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@male_transaksi.errors.count, "error") %> prohibited this male_transaksi from being saved:</h4>

      <ul>
      <% @male_transaksi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :akun, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :akun, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deskripsi, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :deskripsi, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nominal, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nominal, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tipe_relasi, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tipe_relasi, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :jurnal, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :jurnal, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/male_transaksis/edit.html.erb
<div class="page-header">
  <%= link_to male_transaksis_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @male_transaksi, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing male_transaksi</h1>
</div>

<%= render 'form' %>

app/views/male_transaksis/index.html.erb
<div class="page-header">
  <%= link_to new_male_transaksi_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Male transaksi
  <% end %>
  <h1>Listing male_transaksis</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Akun</th>
            <th>Deskripsi</th>
            <th>Nominal</th>
            <th>Tipe relasi</th>
            <th>Jurnal</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @male_transaksis) do |male_transaksi| %>
            <td><%= male_transaksi.akun %></td>
            <td><%= male_transaksi.deskripsi %></td>
            <td><%= male_transaksi.nominal %></td>
            <td><%= male_transaksi.tipe_relasi %></td>
            <td><%= male_transaksi.jurnal %></td>
            <td><%= link_to 'Show', male_transaksi %></td>
        <td><%= link_to 'Edit', edit_male_transaksi_path(male_transaksi) %></td>
        <td><%= link_to 'Destroy', male_transaksi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/male_transaksis/new.html.erb
<div class="page-header">
  <%= link_to male_transaksis_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New male_transaksi</h1>
</div>

<%= render 'form' %>

app/views/male_transaksis/show.html.erb
<div class="page-header">
  <%= link_to male_transaksis_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_male_transaksi_path(@male_transaksi), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show male_transaksi</h1>
</div>

<dl class="dl-horizontal">
  <dt>Akun:</dt>
  <dd><%= @male_transaksi.akun %></dd>

  <dt>Deskripsi:</dt>
  <dd><%= @male_transaksi.deskripsi %></dd>

  <dt>Nominal:</dt>
  <dd><%= @male_transaksi.nominal %></dd>

  <dt>Tipe relasi:</dt>
  <dd><%= @male_transaksi.tipe_relasi %></dd>

  <dt>Jurnal:</dt>
  <dd><%= @male_transaksi.jurnal %></dd>

</dl>