config/routes.rb
Rails.application.routes.draw do
  resources :female_transaksis
  resources :male_transaksis
  resources :koleksi_jurnals
  resources :akuns
  devise_for :users
end

app/models/female_transaksi.rb
class FemaleTransaksi < ApplicationRecord
  belongs_to :akun
  belongs_to :tipe_relasi
  belongs_to :jurnal
end

app/controllers/female_transaksis_controller.rb
class FemaleTransaksisController < ApplicationController
  before_action :set_female_transaksi, only: [:show, :edit, :update, :destroy]

  # GET /female_transaksis
  def index
    @female_transaksis = FemaleTransaksi.all
  end

  # GET /female_transaksis/1
  def show
  end

  # GET /female_transaksis/new
  def new
    @female_transaksi = FemaleTransaksi.new
  end

  # GET /female_transaksis/1/edit
  def edit
  end

  # POST /female_transaksis
  def create
    @female_transaksi = FemaleTransaksi.new(female_transaksi_params)

    if @female_transaksi.save
      redirect_to @female_transaksi, notice: 'Female transaksi was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /female_transaksis/1
  def update
    if @female_transaksi.update(female_transaksi_params)
      redirect_to @female_transaksi, notice: 'Female transaksi was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /female_transaksis/1
  def destroy
    @female_transaksi.destroy
    redirect_to female_transaksis_url, notice: 'Female transaksi was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_female_transaksi
      @female_transaksi = FemaleTransaksi.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def female_transaksi_params
      params.require(:female_transaksi).permit(:akun_id, :deskripsi, :nominal, :tipe_relasi_id, :jurnal_id)
    end
end

app/helpers/female_transaksis_helper.rb
module FemaleTransaksisHelper
end

app/views/female_transaksis/_form.html.erb
<%= form_for(@female_transaksi, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @female_transaksi.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@female_transaksi.errors.count, "error") %> prohibited this female_transaksi from being saved:</h4>

      <ul>
      <% @female_transaksi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :akun, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :akun, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deskripsi, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :deskripsi, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nominal, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nominal, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tipe_relasi, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :tipe_relasi, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :jurnal, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :jurnal, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/female_transaksis/edit.html.erb
<div class="page-header">
  <%= link_to female_transaksis_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @female_transaksi, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing female_transaksi</h1>
</div>

<%= render 'form' %>

app/views/female_transaksis/index.html.erb
<div class="page-header">
  <%= link_to new_female_transaksi_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Female transaksi
  <% end %>
  <h1>Listing female_transaksis</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Akun</th>
            <th>Deskripsi</th>
            <th>Nominal</th>
            <th>Tipe relasi</th>
            <th>Jurnal</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @female_transaksis) do |female_transaksi| %>
            <td><%= female_transaksi.akun %></td>
            <td><%= female_transaksi.deskripsi %></td>
            <td><%= female_transaksi.nominal %></td>
            <td><%= female_transaksi.tipe_relasi %></td>
            <td><%= female_transaksi.jurnal %></td>
            <td><%= link_to 'Show', female_transaksi %></td>
        <td><%= link_to 'Edit', edit_female_transaksi_path(female_transaksi) %></td>
        <td><%= link_to 'Destroy', female_transaksi, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/female_transaksis/new.html.erb
<div class="page-header">
  <%= link_to female_transaksis_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New female_transaksi</h1>
</div>

<%= render 'form' %>

app/views/female_transaksis/show.html.erb
<div class="page-header">
  <%= link_to female_transaksis_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_female_transaksi_path(@female_transaksi), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show female_transaksi</h1>
</div>

<dl class="dl-horizontal">
  <dt>Akun:</dt>
  <dd><%= @female_transaksi.akun %></dd>

  <dt>Deskripsi:</dt>
  <dd><%= @female_transaksi.deskripsi %></dd>

  <dt>Nominal:</dt>
  <dd><%= @female_transaksi.nominal %></dd>

  <dt>Tipe relasi:</dt>
  <dd><%= @female_transaksi.tipe_relasi %></dd>

  <dt>Jurnal:</dt>
  <dd><%= @female_transaksi.jurnal %></dd>

</dl>